CREATE TABLE G21_PERMISOS (
    id_permiso int  NOT NULL,
    nombre_permiso varchar(150)  NOT NULL,
    CONSTRAINT PK_G21_PERMISOS PRIMARY KEY (id_permiso)
);

CREATE UNIQUE INDEX user_id ON G21_USUARIO (e_mail);

ALTER TABLE G21_USUARIO
ADD COLUMN id_permiso int;

ALTER TABLE G21_USUARIO ADD CONSTRAINT FK_G21_USUARIO_PERMISOS
    FOREIGN KEY (id_permiso)
    REFERENCES G21_PERMISOS (id_permiso)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;